/**
 * Tela de Termos de Uso
 *
 * Exibe os termos de uso da assinatura
 */

import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation } from '@react-navigation/native';
import { useLanguage } from '../context/LanguageContext';
import { getThemeColors, fonts, spacing, borderRadius } from '../utils/theme';

export function TermsScreen() {
  const navigation = useNavigation();
  const { theme, t, language } = useLanguage();
  const themeColors = getThemeColors(theme);
  const isMasculine = theme === 'masculine';

  const gradientColors = isMasculine
    ? ['#0F0F1A', '#1A1A2E', '#16213E'] as const
    : ['#87CEEB', '#E0F6FF', '#FFF5E1'] as const;

  // Termos em múltiplos idiomas
  const terms = {
    en: {
      title: 'Terms of Use',
      lastUpdated: 'Last updated: January 2026',
      sections: [
        {
          title: '1. Subscription',
          content: `The subscription is monthly and automatically renewed at the end of each billing cycle. Payment is processed through the App Store (iOS) or Google Play (Android).

You can choose between two plans:
• CandyCandy: $9.99/month - Up to 150 recipes per month
• CandyCandy Basic: $4.99/month - Up to 60 recipes per month

Prices may vary by region and local currency. The displayed price is always in your local currency.`,
        },
        {
          title: '2. Monthly Limits',
          content: `Each subscription plan has a monthly limit of recipe generations:
• Limits reset at the beginning of each billing cycle
• Unused limits do NOT carry over to the next month
• When the limit is reached, you must wait for the next cycle or upgrade your plan`,
        },
        {
          title: '3. Cancellation',
          content: `You can cancel your subscription at any time through your device settings:
• iOS: Settings > Apple ID > Subscriptions
• Android: Google Play > Subscriptions

After cancellation:
• Premium access remains until the end of the paid period
• No refund for partial months
• You can resubscribe at any time`,
        },
        {
          title: '4. Refund',
          content: `Refunds are processed according to Apple App Store or Google Play policies. Contact the respective store for refund requests.`,
        },
        {
          title: '5. Content',
          content: `Recipes are generated by artificial intelligence and are for entertainment and educational purposes. Always have adult supervision when preparing recipes with children.`,
        },
        {
          title: '6. Changes',
          content: `We reserve the right to modify these terms. Changes will be notified within the app. Continued use of the service after modifications implies acceptance of the new terms.`,
        },
      ],
    },
    pt: {
      title: 'Termos de Uso',
      lastUpdated: 'Última atualização: Janeiro 2026',
      sections: [
        {
          title: '1. Assinatura',
          content: `A assinatura é mensal e renovada automaticamente ao final de cada ciclo de cobrança. O pagamento é processado pela App Store (iOS) ou Google Play (Android).

Você pode escolher entre dois planos:
• CandyCandy: $9,99/mês - Até 150 receitas por mês
• CandyCandy Basic: $4,99/mês - Até 60 receitas por mês

Os preços podem variar conforme a região e moeda local. O preço exibido é sempre na sua moeda local.`,
        },
        {
          title: '2. Limites Mensais',
          content: `Cada plano de assinatura possui um limite mensal de gerações de receitas:
• Os limites são resetados no início de cada ciclo de cobrança
• Limites não utilizados NÃO acumulam para o mês seguinte
• Ao atingir o limite, você deve aguardar o próximo ciclo ou fazer upgrade do plano`,
        },
        {
          title: '3. Cancelamento',
          content: `O cancelamento pode ser feito a qualquer momento nas configurações do seu dispositivo:
• iOS: Ajustes > Apple ID > Assinaturas
• Android: Google Play > Assinaturas

Após o cancelamento:
• O acesso premium permanece até o final do período pago
• Não há reembolso por meses parciais
• Você pode reassinar a qualquer momento`,
        },
        {
          title: '4. Reembolso',
          content: `Reembolsos são processados de acordo com as políticas da Apple App Store ou Google Play. Entre em contato com a respectiva loja para solicitar reembolso.`,
        },
        {
          title: '5. Conteúdo',
          content: `As receitas são geradas por inteligência artificial e são para fins de entretenimento e educacionais. Sempre tenha supervisão de um adulto ao preparar receitas com crianças.`,
        },
        {
          title: '6. Alterações',
          content: `Reservamos o direito de modificar estes termos. Alterações serão comunicadas dentro do aplicativo. O uso continuado do serviço após modificações implica na aceitação dos novos termos.`,
        },
      ],
    },
    es: {
      title: 'Términos de Uso',
      lastUpdated: 'Última actualización: Enero 2026',
      sections: [
        {
          title: '1. Suscripción',
          content: `La suscripción es mensual y se renueva automáticamente al final de cada ciclo de facturación. El pago se procesa a través de la App Store (iOS) o Google Play (Android).

Puedes elegir entre dos planes:
• CandyCandy: $9.99/mes - Hasta 150 recetas por mes
• CandyCandy Basic: $4.99/mes - Hasta 60 recetas por mes

Los precios pueden variar según la región y la moneda local.`,
        },
        {
          title: '2. Límites Mensuales',
          content: `Cada plan tiene un límite mensual de generaciones:
• Los límites se reinician al inicio de cada ciclo
• Los límites no utilizados NO se acumulan
• Al alcanzar el límite, debes esperar el próximo ciclo`,
        },
        {
          title: '3. Cancelación',
          content: `Puedes cancelar en cualquier momento en la configuración de tu dispositivo.`,
        },
        {
          title: '4. Reembolso',
          content: `Los reembolsos se procesan según las políticas de Apple o Google Play.`,
        },
        {
          title: '5. Contenido',
          content: `Las recetas son generadas por IA y son para entretenimiento. Siempre con supervisión de adultos.`,
        },
        {
          title: '6. Cambios',
          content: `Nos reservamos el derecho de modificar estos términos.`,
        },
      ],
    },
  };

  // Fallback para inglês se o idioma não estiver disponível
  const currentTerms = terms[language as keyof typeof terms] || terms.en;

  return (
    <LinearGradient colors={gradientColors} style={styles.gradient}>
      <SafeAreaView style={styles.container}>
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity
            onPress={() => navigation.goBack()}
            style={[styles.backButton, { backgroundColor: themeColors.card }]}
          >
            <Text style={[styles.backText, { color: themeColors.text }]}>←</Text>
          </TouchableOpacity>
          <Text style={[styles.title, { color: themeColors.text }]}>
            📄 {currentTerms.title}
          </Text>
          <View style={styles.placeholder} />
        </View>

        <ScrollView
          style={styles.scrollView}
          contentContainerStyle={styles.content}
          showsVerticalScrollIndicator={false}
        >
          {/* Data de atualização */}
          <Text style={[styles.lastUpdated, { color: themeColors.textSecondary }]}>
            {currentTerms.lastUpdated}
          </Text>

          {/* Seções dos termos */}
          {currentTerms.sections.map((section, index) => (
            <View
              key={index}
              style={[
                styles.section,
                { backgroundColor: themeColors.card },
              ]}
            >
              <Text style={[styles.sectionTitle, { color: themeColors.primary }]}>
                {section.title}
              </Text>
              <Text style={[styles.sectionContent, { color: themeColors.text }]}>
                {section.content}
              </Text>
            </View>
          ))}

          {/* Contato */}
          <View style={[styles.contactBox, { backgroundColor: themeColors.card }]}>
            <Text style={[styles.contactTitle, { color: themeColors.text }]}>
              📧 {language === 'pt' ? 'Contato' : 'Contact'}
            </Text>
            <Text style={[styles.contactText, { color: themeColors.textSecondary }]}>
              support@magicsweetmaker.com
            </Text>
          </View>

          {/* Decoração */}
          <View style={styles.decoration}>
            {(isMasculine ? ['🦸', '⚡', '💪'] : ['🧁', '🍰', '🍭']).map((e, i) => (
              <Text key={i} style={styles.decorEmoji}>{e}</Text>
            ))}
          </View>
        </ScrollView>
      </SafeAreaView>
    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  gradient: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backText: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  title: {
    fontSize: fonts.sizes.xl,
    fontWeight: 'bold',
  },
  placeholder: {
    width: 44,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: spacing.lg,
  },
  lastUpdated: {
    fontSize: fonts.sizes.sm,
    marginBottom: spacing.lg,
    textAlign: 'center',
  },
  section: {
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontSize: fonts.sizes.md,
    fontWeight: 'bold',
    marginBottom: spacing.sm,
  },
  sectionContent: {
    fontSize: fonts.sizes.sm,
    lineHeight: 22,
  },
  contactBox: {
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    marginTop: spacing.md,
    alignItems: 'center',
  },
  contactTitle: {
    fontSize: fonts.sizes.md,
    fontWeight: 'bold',
    marginBottom: spacing.xs,
  },
  contactText: {
    fontSize: fonts.sizes.sm,
  },
  decoration: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: spacing.md,
    marginTop: spacing.xl,
    marginBottom: spacing.xxl,
  },
  decorEmoji: {
    fontSize: 32,
    opacity: 0.6,
  },
});
